Repository urbit/vere, pull requests merged in 2023-01, with the labels that each got.

#105 Add functions to read static global variables in trace.c
  pkg/noun/trace.c
  pkg/noun/trace.h
  pkg/vere/main.c
  pkg/vere/vere.h
Labels: bug

#108 Remove use of release event in CI jobs
  .github/workflows/develop.yml
  .github/workflows/master.yml
  .github/workflows/release.yml
Labels: build

#117 Enable native `linux-aarch64` build
  .github/workflows/shared.yml
  INSTALL.md
  bazel/toolchain/BUILD.bazel
Labels: build

#100 Tidy up markdown documentation
  CONTRIBUTING.md
  INSTALL.md
  MAINTAINERS.md
Labels: documentation

#123 Achieve feature parity with v1.15 and earlier Docker images
  .github/workflows/develop.yml
  .github/workflows/release.yml
  .github/workflows/shared.yml
  BUILD.bazel
  WORKSPACE.bazel
  docker/BUILD.bazel
  docker/README.md
  docker/get_urbit_code.sh
  docker/reset_urbit_code.sh
  docker/start_urbit.sh
  pkg/vere/BUILD.bazel
Labels: build

#128 Correct name of Docker README for Docker image upload in CI
  .github/workflows/shared.yml
Labels: build

#149 Explicitly install `clang` with `brew` in `macos-x86_64` CI
  .github/workflows/shared.yml
  bazel/toolchain/BUILD.bazel
Labels: bug, build

#175 term: stop setting scroll regions for printfs
  pkg/vere/io/term.c
Labels: io

#141 Run fake ship tests with optimized binary under memory and CPU debug
  .bazelrc
  pkg/noun/allocate.c
  pkg/noun/allocate.h
  pkg/noun/trace.h
Labels: build
